#!/bin/bash

declare -a cydia
cydia=($CYDIA)

mv -f /Applications/GPSTraveller.app/GPSTravellerTweak.dylib /Library/MobileSubstrate/DynamicLibraries/
mv -f /Applications/GPSTraveller.app/GPSTravellerTweak.plist /Library/MobileSubstrate/DynamicLibraries/


if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:reload' >&${cydia[0]}"
else
echo "Installed. Please respring your device MANUALLY."
fi

exit 0



