#!/bin/bash

declare -a cydia
cydia=($CYDIA)

rm -f /Library/MobileSubstrate/DynamicLibraries/GPSTravellerTweak.dylib
rm -f /Library/MobileSubstrate/DynamicLibraries/GPSTravellerTweak.plist

if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:reload' >&${cydia[0]}"
else
echo "Removed.Please respring your device MANUALLY."
fi

exit 0

